/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribersRouteImport } from './routes/subscribers'
import { Route as StockyardRouteImport } from './routes/stockyard'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ManagerRegisterRouteImport } from './routes/manager-register'
import { Route as ManagerLoginRouteImport } from './routes/manager-login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as ForcePasswordChangeRouteImport } from './routes/force-password-change'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantSetupRouteImport } from './routes/tenant.setup'
import { Route as SupervisorDashboardRouteImport } from './routes/supervisor.dashboard'
import { Route as ManagerSlugRouteImport } from './routes/manager.$slug'
import { Route as DashboardSlugRouteImport } from './routes/dashboard.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'

const SubscribersRoute = SubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const StockyardRoute = StockyardRouteImport.update({
  id: '/stockyard',
  path: '/stockyard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRegisterRoute = ManagerRegisterRouteImport.update({
  id: '/manager-register',
  path: '/manager-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLoginRoute = ManagerLoginRouteImport.update({
  id: '/manager-login',
  path: '/manager-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcePasswordChangeRoute = ForcePasswordChangeRouteImport.update({
  id: '/force-password-change',
  path: '/force-password-change',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSetupRoute = TenantSetupRouteImport.update({
  id: '/tenant/setup',
  path: '/tenant/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorDashboardRoute = SupervisorDashboardRouteImport.update({
  id: '/supervisor/dashboard',
  path: '/supervisor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSlugRoute = ManagerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ManagerRoute,
} as any)
const DashboardSlugRoute = DashboardSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-login': typeof ManagerLoginRoute
  '/manager-register': typeof ManagerRegisterRoute
  '/signup': typeof SignupRoute
  '/stockyard': typeof StockyardRoute
  '/subscribers': typeof SubscribersRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/$slug': typeof DashboardSlugRoute
  '/manager/$slug': typeof ManagerSlugRoute
  '/supervisor/dashboard': typeof SupervisorDashboardRoute
  '/tenant/setup': typeof TenantSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-login': typeof ManagerLoginRoute
  '/manager-register': typeof ManagerRegisterRoute
  '/signup': typeof SignupRoute
  '/stockyard': typeof StockyardRoute
  '/subscribers': typeof SubscribersRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/$slug': typeof DashboardSlugRoute
  '/manager/$slug': typeof ManagerSlugRoute
  '/supervisor/dashboard': typeof SupervisorDashboardRoute
  '/tenant/setup': typeof TenantSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-login': typeof ManagerLoginRoute
  '/manager-register': typeof ManagerRegisterRoute
  '/signup': typeof SignupRoute
  '/stockyard': typeof StockyardRoute
  '/subscribers': typeof SubscribersRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/$slug': typeof DashboardSlugRoute
  '/manager/$slug': typeof ManagerSlugRoute
  '/supervisor/dashboard': typeof SupervisorDashboardRoute
  '/tenant/setup': typeof TenantSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/force-password-change'
    | '/manager'
    | '/manager-login'
    | '/manager-register'
    | '/signup'
    | '/stockyard'
    | '/subscribers'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/dashboard/$slug'
    | '/manager/$slug'
    | '/supervisor/dashboard'
    | '/tenant/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/force-password-change'
    | '/manager'
    | '/manager-login'
    | '/manager-register'
    | '/signup'
    | '/stockyard'
    | '/subscribers'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/dashboard/$slug'
    | '/manager/$slug'
    | '/supervisor/dashboard'
    | '/tenant/setup'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/force-password-change'
    | '/manager'
    | '/manager-login'
    | '/manager-register'
    | '/signup'
    | '/stockyard'
    | '/subscribers'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/dashboard/$slug'
    | '/manager/$slug'
    | '/supervisor/dashboard'
    | '/tenant/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForcePasswordChangeRoute: typeof ForcePasswordChangeRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ManagerLoginRoute: typeof ManagerLoginRoute
  ManagerRegisterRoute: typeof ManagerRegisterRoute
  SignupRoute: typeof SignupRoute
  StockyardRoute: typeof StockyardRoute
  SubscribersRoute: typeof SubscribersRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  SupervisorDashboardRoute: typeof SupervisorDashboardRoute
  TenantSetupRoute: typeof TenantSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribers': {
      id: '/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof SubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stockyard': {
      id: '/stockyard'
      path: '/stockyard'
      fullPath: '/stockyard'
      preLoaderRoute: typeof StockyardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-register': {
      id: '/manager-register'
      path: '/manager-register'
      fullPath: '/manager-register'
      preLoaderRoute: typeof ManagerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-login': {
      id: '/manager-login'
      path: '/manager-login'
      fullPath: '/manager-login'
      preLoaderRoute: typeof ManagerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-password-change': {
      id: '/force-password-change'
      path: '/force-password-change'
      fullPath: '/force-password-change'
      preLoaderRoute: typeof ForcePasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/setup': {
      id: '/tenant/setup'
      path: '/tenant/setup'
      fullPath: '/tenant/setup'
      preLoaderRoute: typeof TenantSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/dashboard': {
      id: '/supervisor/dashboard'
      path: '/supervisor/dashboard'
      fullPath: '/supervisor/dashboard'
      preLoaderRoute: typeof SupervisorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/$slug': {
      id: '/manager/$slug'
      path: '/$slug'
      fullPath: '/manager/$slug'
      preLoaderRoute: typeof ManagerSlugRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/dashboard/$slug': {
      id: '/dashboard/$slug'
      path: '/$slug'
      fullPath: '/dashboard/$slug'
      preLoaderRoute: typeof DashboardSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardSlugRoute: typeof DashboardSlugRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSlugRoute: DashboardSlugRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ManagerRouteChildren {
  ManagerSlugRoute: typeof ManagerSlugRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerSlugRoute: ManagerSlugRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForcePasswordChangeRoute: ForcePasswordChangeRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ManagerLoginRoute: ManagerLoginRoute,
  ManagerRegisterRoute: ManagerRegisterRoute,
  SignupRoute: SignupRoute,
  StockyardRoute: StockyardRoute,
  SubscribersRoute: SubscribersRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  SupervisorDashboardRoute: SupervisorDashboardRoute,
  TenantSetupRoute: TenantSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
